# pgRecovery function recover a PostgreSQL database
apiVersion: stash.appscode.com/v1beta1
kind: Function
metadata:
  name: pgRecovery
spec:
  image:  appscodeci/postgresql-tool:v1
  name:  postgres-tool
  args:
  - recover
  - --provider=${provider}
  - --hostname=${hostname}
  - --path=${repoDir}
  - --output-dir=${outputDir}
  - --metrics.enabled=${enableMetric}
  - --metrics.pushgateway-url=${pushgatewayURL}
  - --metrics.labels="workload-kind=${workloadKind},workload-name=${workloadName}"
  runtimeSettings:
    env:
    - name:  PGPASSWORD
      valueFrom:
        secretKeyRef:
          name: $(databaseSecret)
          key: "POSTGRES_PASSWORD"
    - name:  DB_USER
      valueFrom:
        secretKeyRef:
          name: $(databaseSecret)
          key: "POSTGRES_USER"
    - name:  DB_HOST
      value: $(host)
  volumeMounts:
  - name: ${tempVolumeName}
    mountPath: /tmp/restic
  - name: ${storageSecretName}
    mountPath: /etc/secrets/storage-secret
