title: Backup your Kubernetes Stateful Applications
baseurl: https://stash.run
languageCode: en-us
assetDir: static
googleAnalytics: UA-62096468-4
disableKinds:
- taxonomy
- taxonomyTerm
params:
  product_key: stash
  main_menu_dropdown_item: database
  domain_appscode: https://appscode.com
  domain_voyagermesh: https://voyagermesh.com
  domain_stash: https://stash.run
  domain_kubedb: https://kubedb.com
  domain_kubevault: https://kubevault.com
  domain_kubeform: https://kubeform.com
  domain_pharmer: https://pharmer.dev
  domain_kubeci: https://kube.ci
  domain_kubeshield: https://kubeshield.com
  domain_bytebuilders: https://byte.builders
  domain_marketplace: https://marketplace.byte.builders
  search_engine_ID: 015199383701854252104:0pfqfvpvwyl
  search_api_key: _replace_
  blog_url: https://blog.byte.builders
  slack_url: https://slack.appscode.com
  github_url: https://github.com/appscode
  twitter_url: https://twitter.com/AppsCodeHQ
  facebook_url: https://www.facebook.com/appscode
  youtube_url: https://www.youtube.com/c/AppsCodeInc
  contact_email: support@appscode.com
  contact_phone: +1(650)241-8486
  comments:
    enable: true
    giscus:
      repo: bytebuilders/community
      repoId: R_kgDOG-h6rw
      category: Stash
      categoryId: DIC_kwDOG-h6r84COCFw
      map: title
menu:
  main:
  - name: Documentation
    weight: 20
  addons:
  - name: Elasticsearch
    identifier: elasticsearch
    parent: addons
    weight: 10
    pre: /assets/images/addons/logos/elasticsearch.svg
  - name: MariaDB
    identifier: mariadb
    parent: addons
    weight: 20
    pre: /assets/images/addons/logos/mariadbs.svg
  - name: MongoDB
    identifier: mongodb
    parent: addons
    weight: 40
    pre: /assets/images/addons/logos/mongodb.svg
  - name: MySQL
    identifier: mysql
    parent: addons
    weight: 50
    pre: /assets/images/addons/logos/mysql.svg
  - name: Percona XtraDB
    identifier: percona-xtradb
    parent: addons
    weight: 60
    pre: /assets/images/addons/logos/perconaxtradbs.svg
  - name: Postgres
    identifier: postgres
    parent: addons
    weight: 80
    pre: /assets/images/addons/logos/postgres.svg
  - name: Redis
    identifier: redis
    parent: addons
    weight: 100
    pre: /assets/images/addons/logos/redis.svg
  - name: NATS
    identifier: nats
    parent: addons
    weight: 100
    pre: /assets/images/addons/logos/nats.svg
  - name: Etcd
    identifier: etcd
    parent: addons
    weight: 100
    pre: /assets/images/addons/logos/etcd.svg
markup:
  goldmark:
    renderer:
      unsafe: true
  highlight:
    style: manni
