# stashPostRecovery update RecoveryConfiguration status for respective recovery
apiVersion: stash.appscode.com/v1beta1
kind: Function
metadata:
  name: stashPostRecovery
spec:
  image: appscode/stash:0.9.0
  name:  stash-post-recovery
  args:
  - post-recovery-update
  - --recoveryconfiguration=${recoveryConfigurationName}
  - --output-json-dir=${outputJsonDir}
  volumeMounts:
  - name: ${outputVolumeName}
    mountPath: /tmp/restic
