apiVersion: kubedb.com/v1alpha1
kind: PerconaXtraDB
metadata:
  name: restored-xtradb-cluster
  namespace: demo
spec:
  version: "5.7-cluster"
  replicas: 3
  databaseSecret:
    secretName: sample-xtradb-cluster-auth
  storageType: Durable
  storage:
    storageClassName: "standard"
    accessModes:
    - ReadWriteOnce
    resources:
      requests:
        storage: 1Gi
  init:
    stashRestoreSession:
      name: restored-xtradb-cluster-restore
  terminationPolicy: WipeOut
